# Use official Maven + JDK base image
FROM maven:3.9.6-eclipse-temurin-21 AS build

WORKDIR /app

# Copy pom + source
COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src ./src

# Build the JAR
RUN mvn package -DskipTests


# Final image
FROM eclipse-temurin:21-jdk
WORKDIR /app

COPY --from=build /app/target/backend-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]